### ISSUE TITLE
建议： 把 tauri  版本 合并到 vue-xs-admin， 不单独维护

### ISSUE THREAD

**Issue by hhstore** [jsxiaosi/tauri-xs-admin#1]
# 如题： 

- `tauri` 版本， 并没有多少 tauri 代码， 单独维护，和主repo， 同步很麻烦。
- `vue-xs-admin` 改成 monorepo 目录结构， 如

```ruby

packages/
    vue-xs-admin/
        src/          # 前端代码
        src-tauri/    # tauri 部分
    min-xs-admin/

```

- 都在 `vue-xs-admin` 里维护， 更新也方便。

**Comment by jsxiaosi** [comment]
当初做这个项目的时候是为了能够让vue-xs-admin能够尝试在不同的框架（tauri、electron）上构建跨平台，所以才单独了一个项目出来，emmm~！或者说tauri只是vue-xs-admin的一个扩展，并不属于这个项目的主要功能吧~！不过你的建议对我很有帮助，我会把它列入到我的计划，当然我也非常欢迎你提交PR~！再次感谢你提供宝贵的建议~！

**Comment by hhstore** [comment]
> 当初做这个项目的时候是为了能够让vue-xs-admin能够尝试在不同的框架（tauri、electron）上构建跨平台，所以才单独了一个项目出来，emmm~！或者说tauri只是vue-xs-admin的一个扩展，并不属于这个项目的主要功能吧~！不过你的建议对我很有帮助，我会把它列入到我的计划，当然我也非常欢迎你提交PR~！再次感谢你提供宝贵的建议~！

想了一下， 也可以把这个repo删了， fork 主 repo， 重命名成这个 repo。

这样也解决主 repo 代码同步问题。

**Comment by jsxiaosi** [comment]
> > 当初做这个项目的时候是为了能够让vue-xs-admin能够尝试在不同的框架（tauri、electron）上构建跨平台，所以才单独了一个项目出来，emmm~！或者说tauri只是vue-xs-admin的一个扩展，并不属于这个项目的主要功能吧~！不过你的建议对我很有帮助，我会把它列入到我的计划，当然我也非常欢迎你提交PR~！再次感谢你提供宝贵的建议~！
> 
> 想了一下， 也可以把这个repo删了， fork 主 repo， 重命名成这个 repo。
> 
> 这样也解决主 repo 代码同步问题。

自己不能fork自己的project 但是我目前也是参照这个方式来做的，我要同步vue-xs-admin的代码的时候我直接在tauri项目上拉取vue-xs-admin的main分支代码下来就可以合并了

**Comment by hhstore** [comment]
- 自己不能 fork 自己的 repo， 有`折衷`办法。
- 你创建一个组织 `org X`， 把 A repo 迁移到 X， 然后去 X 下 fork 到自己`个人账户`， repo 改个名字， 再把 repo 所有权， 转移到 `org X` 下， 即可。 

> ps： 

- 你 git remote 添加 `mirror upstream` 到 `源repo`， 手动 sync `源 repo`， 也可。 
- fork 自己的方式， 维护更简单一点， 也方便你后续如果想把`子repo`的修改， 合并到 `源repo`。

**Comment by jsxiaosi** [comment]
> * 自己不能 fork 自己的 repo， 有`折衷`办法。
> * 你创建一个组织 `org X`， 把 A repo 迁移到 X， 然后去 X 下 fork 到自己`个人账户`， repo 改个名字， 再把 repo 所有权， 转移到 `org X` 下， 即可。
> 
> > ps：
> 
> * 你 git remote 添加 `mirror upstream` 到 `源repo`， 手动 sync `源 repo`， 也可。
> * fork 自己的方式， 维护更简单一点， 也方便你后续如果想把`子repo`的修改， 合并到 `源repo`。

这个确实是个不错的主意~！晚点有时间我弄一下试一下
